/**
* This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  count: number;
}
export type ExecuteMsg = {
  update_config: {};
} | {
  increment: {};
} | {
  reset: {
    count: number;
  };
} | {
  trade: {
    data: Trade;
  };
} | {
  trade_ciphertext: {
    ciphertext: number[];
    digest: HexBinary;
  };
};
export type OrderType = "market";
export type Decimal = string;
export type HexBinary = string;
export interface Trade {
  asset: string;
  buy: boolean;
  dt: number;
  expire_time: number;
  order_type: OrderType;
  price: Decimal;
  qty: Decimal;
  sl: Decimal;
  tp: Decimal;
}
export type QueryMsg = {
  config: {};
} | {
  query_trade: {
    base: string;
    quote: string;
  };
};
export interface MigrateMsg {}
export interface ConfigResponse {}
export interface TradeResponse {
  price: GetPriceResponse;
  trade: Trade;
}
export interface GetPriceResponse {
  decimals: number;
  id: number;
  nonce: number;
  price?: QuotePrice | null;
}
export interface QuotePrice {
  block_height: number;
  block_timestamp?: Timestamp | null;
  price: string;
}
export interface Timestamp {
  nanos: number;
  seconds: number;
}