/**
* This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  count: number;
}
export type ExecuteMsg = {
  update_config: {};
} | {
  increment: {};
} | {
  reset: {
    count: number;
  };
};
export type QueryMsg = {
  config: {};
} | {
  count: {};
};
export interface MigrateMsg {}
export interface ConfigResponse {}
export interface CountResponse {
  count: number;
}