// @ts-nocheck
          /**
* This file was automatically generated by @abstract-money/ts-codegen@0.37.0-beta-3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, ConfigResponse, CountResponse } from "./Pop.types";
import { CamelCasedProperties } from "type-fest";
export abstract class PopExecuteMsgBuilder {
static updateConfig = (): ExecuteMsg => {
  return {
    update_config: ({} as const)
  };
};
static increment = (): ExecuteMsg => {
  return {
    increment: ({} as const)
  };
};
static reset = ({
  count
}: CamelCasedProperties<Extract<ExecuteMsg, {
  reset: unknown;
}>["reset"]>): ExecuteMsg => {
  return {
    reset: ({
      count
    } as const)
  };
};
}
export abstract class PopQueryMsgBuilder {
static config = (): QueryMsg => {
  return {
    config: ({} as const)
  };
};
static count = (): QueryMsg => {
  return {
    count: ({} as const)
  };
};
}